"""Read a cut-list CSV and generate a Fusion 360 Python script."""
import csv
import io
from pathlib import Path


def build_fusion_script(csv_content: str, project_name: str = "kitchen") -> str:
    """Return a Fusion 360 .py script string from cut-list CSV content."""
    panels = _parse_csv(csv_content)
    return _render_script(panels, project_name)


def build_fusion_script_from_file(csv_path: str | Path, project_name: str = "kitchen") -> str:
    content = Path(csv_path).read_text(encoding="utf-8")
    return build_fusion_script(content, project_name)


def _parse_csv(csv_content: str) -> list[dict]:
    reader = csv.DictReader(io.StringIO(csv_content))
    return list(reader)


def _render_script(panels: list[dict], project_name: str) -> str:
    lines = [
        "import adsk.core, adsk.fusion, traceback",
        "",
        "def run(context):",
        "    ui = None",
        "    try:",
        "        app = adsk.core.Application.get()",
        "        ui = app.userInterface",
        "        design = app.activeProduct",
        "        root = design.rootComponent",
        f"        # Generated by Kalitron AI Gateway — project: {project_name}",
        "",
    ]

    for panel in panels:
        part = panel.get("part", "Panel").replace(" ", "_")
        try:
            w = float(panel.get("width_cm", 0)) / 100  # cm → m
            h = float(panel.get("height_cm", 0)) / 100
            t = float(panel.get("thickness_mm", 18)) / 1000  # mm → m
            qty = int(panel.get("qty", 1))
        except (ValueError, TypeError):
            continue

        lines += [
            f"        # {panel.get('part', part)} × {qty}",
            f"        sketches_{part} = root.sketches",
            f"        xy_{part} = root.xYConstructionPlane",
            f"        sketch_{part} = sketches_{part}.add(xy_{part})",
            f"        lines_{part} = sketch_{part}.sketchCurves.sketchLines",
            f"        lines_{part}.addTwoPointRectangle(",
            f"            adsk.core.Point3D.create(0, 0, 0),",
            f"            adsk.core.Point3D.create({w}, {h}, 0)",
            f"        )",
            f"        prof_{part} = sketch_{part}.profiles.item(0)",
            f"        extrudes_{part} = root.features.extrudeFeatures",
            f"        ext_input_{part} = extrudes_{part}.createInput(prof_{part}, adsk.fusion.FeatureOperations.NewBodyFeatureOperation)",
            f"        ext_input_{part}.setDistanceExtent(False, adsk.core.ValueInput.createByReal({t}))",
            f"        extrudes_{part}.add(ext_input_{part})",
            "",
        ]

    lines += [
        "        ui.messageBox('Kalitron cut list imported successfully!')",
        "    except:",
        "        if ui:",
        "            ui.messageBox('Failed:\\n{}'.format(traceback.format_exc()))",
    ]

    return "\n".join(lines)
